bufbuild/intellij-buf

- src/test/resources/testData/completion/external/buf.lock
- src/test/resources/testData/resolve/external/buf.lock
Fix the tests in intellij-buf to bump to the latest googleapis/googleapis dependency (the pinned version no longer exists after refactoring this module in the BSR).
> update buf.lock for googleapis change

- .github/workflows/build.yml
- .github/workflows/release.yml
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> Update Github Actions outputs to new format

- src/main/kotlin/build/buf/intellij/resolve/BufCacheLibrary.kt
- src/main/kotlin/build/buf/intellij/resolve/BufRootsProvider.kt
Use a temporary directory to avoid issues with race conditions, perform an atomic move when successful, add error handling and logging, and ensure proper cleanup on error.
> Improve error handling of v2 cache folder

- build.gradle.kts
- build_versions.py
- gradle/libs.versions.toml
Instead of installing the latest license-header binary, we should pin it to the same version as the version of Buf we're using. Upgrade buf to the latest v1.22.0 release, and relax the restriction in the build that we need an Azul toolchain - any Java 11 toolchain should work until we upgrade to Java 17.
> Fix intellij-buf build w/ new buf versions

- .github/workflows/build.yml
- .github/workflows/code_quality.yml
- .github/workflows/release.yml
- .github/workflows/run-ui-tests.yml
- build.gradle.kts
- gradle.properties
- gradle/libs.versions.toml
- gradle/test-intellij.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- qodana.yml
- src/main/kotlin/build/buf/intellij/BufPluginService.kt
- src/main/kotlin/build/buf/intellij/annotator/BufAnalyzePass.kt
- src/main/kotlin/build/buf/intellij/inspections/BufAnalyzeInspection.kt
Update the baseline for the plugin to 2022.3 or later versions. This will allow us to migrate to newer APIs and start compiling on Java 17 (instead of 11).
> Update plugin to require 2022.3 or later

- build.gradle.kts
- src/test/kotlin/build/buf/intellij/base/BufTestBase.kt
Update the tasks to install the Buf CLI and license-header CLI to add outputs to correctly inform the build of what is created.
> Set outputs for buf CLI / license-header

- src/main/kotlin/build/buf/intellij/annotator/BufAnalyzeUtils.kt
- src/main/kotlin/build/buf/intellij/formatter/BufFormatterService.kt
- src/test/kotlin/build/buf/intellij/formatter/BufFormatterTest.kt
- src/test/resources/testData/formatter/largeprotofile-after.proto
- src/test/resources/testData/formatter/largeprotofile-before.proto
The previous implementation of formatting would take each chunk of stdout (up to 8192 chars), trim any trailing newlines, and then join the chunks together with a newline at the end. This causes short inputs to be missing a trailing newline at EOF and also in some cases caused newlines to be inserted in the middle of chunks of a protobuf file causing syntax errors.
Update the plugin to stop trimming the end of stdout chunks and join without newlines, preserving output exactly as-is from buf format. Update the tests to add a new larger file and fix the expected result of the first test to add the trailing newline at EOF. Now both inputs match the output of 'buf format' exactly.
Fixes #180.
> Preserve newlines with buf format

- .github/workflows/build.yml
- build.gradle.kts
- gradle/libs.versions.toml
Instead of needing to go install the Buf CLI with each build, we should pull the dependency from Maven Central (which also has the benefit of caching it).
This also will ensure that dependabot will keep it updated.
> Use buf CLI from Maven Central

- src/main/kotlin/build/buf/intellij/annotator/BufAnalyzeUtils.kt
- src/main/kotlin/build/buf/intellij/index/BufIndexes.kt
- src/main/kotlin/build/buf/intellij/model/BufIssue.kt
- src/test/kotlin/build/buf/intellij/model/BufIssueTest.kt
In BufIndexes, we don't need to search libraries and only need to search across project files to filter the returned buf.yaml/buf.lock index entries. Update BufIssue to use Result class to mirror other classes.
> Reduce scope to only search project files

- src/main/kotlin/build/buf/intellij/annotator/BufAnalyzePass.kt
- src/main/kotlin/build/buf/intellij/annotator/BufAnalyzeUtils.kt
Both the lint and breaking change command are expected to return exit code 100 when issues are found. Update the logging to omit logging these cases so we only log warnings if a real failure occurs trying to run the Buf CLI.
Additionally, add a comment regarding file-level lint warnings (which are currently unsupported).
> Fix logging of expected exit codes

- src/main/kotlin/build/buf/intellij/annotator/BufAnalyzeUtils.kt
- src/main/kotlin/build/buf/intellij/resolve/RefreshAdditionalBufRoots.kt
In order to correctly resolve dependencies and add source roots on startup, we should trigger a 'buf build' on a separate thread during startup to populate the cache with any dependencies.
> Run buf build on startup to prime cache

- src/main/kotlin/build/buf/intellij/index/BufIndexes.kt
Don't return buf.yaml/buf.lock index contents for files which are found in excluded directories.
> Filter out files in excluded directories

- src/main/kotlin/build/buf/intellij/configurable/BufConfigurable.kt
Update the plugin to stop calling tokenizeByWhitespace (this method is not available in 2024.2 EAP).
> Fix compatilbility issue with latest EAP

- src/main/kotlin/build/buf/intellij/annotator/BufAnalyzeUtils.kt
- src/main/kotlin/build/buf/intellij/formatter/BufFormatterService.kt
- src/test/kotlin/build/buf/intellij/formatter/BufFormatterTest.kt
Update formatter to check the exit code of the command, and only reformat the file if it exits with a 0 exit code. If `buf format` returns an error, show up to 10 lines of stderr to help diagnose any issues.
Fixes #273.
> Avoid changing file contents if format failed

- build.gradle.kts
- gradle.properties
- gradle/test-intellij.versions.toml
Mute the TemplateWordInPluginId (we've previously published the plugin) and set a valid pluginUntilBuild setting (this will mean we'll have to periodically re-test and re-publish for new IDE versions).
Bump the plugin verification versions to test with the latest released IIC version.
> Fix plugin verification

- .github/workflows/build.yml
- .gitignore
CI builds are regularly running out of space. Bump to larger runners to attempt to fix.
> Update to larger runners for build jobs

- build.gradle.kts
- gradle/libs.versions.toml
- src/test/kotlin/build/buf/intellij/base/BufTestBase.kt
- src/test/kotlin/build/buf/intellij/cas/CASDigestTest.kt
- src/test/kotlin/build/buf/intellij/cas/FileNodeTest.kt
- src/test/kotlin/build/buf/intellij/cas/ManifestTest.kt
- src/test/kotlin/build/buf/intellij/completion/BufCompletionTest.kt
- src/test/kotlin/build/buf/intellij/model/BufIssueTest.kt
- src/test/kotlin/build/buf/intellij/module/ModuleDigestTest.kt
- src/test/kotlin/build/buf/intellij/module/ModuleFullNameTest.kt
- src/test/kotlin/build/buf/intellij/module/ModuleKeyTest.kt
- src/test/kotlin/build/buf/intellij/module/UUIDUtilsTest.kt
Upgrading to the latest IntelliJ platform plugin is failing with issues related to JUnit 5 in https://github.com/bufbuild/intellij-buf/pull/283. We don't require use of JUnit 5 so migrate to JUnit 4 to make it easier to adopt newer platform plugins.
> Migrate to junit 4

- build.gradle.kts
- gradle.properties
The plugin verification tests are failing in EAP 2025 builds since the Kanro plugin doesn't exist in the marketplace with a supported version. Update the tests to temporarily test up to 2024.3.* builds in the meantime.
> Fix CI plugin verification tests

- src/main/kotlin/build/buf/intellij/module/cache/BaseModuleCache.kt
- src/main/kotlin/build/buf/intellij/module/cache/ModuleCacheV1.kt
- src/main/kotlin/build/buf/intellij/module/cache/ModuleCacheV2.kt
- src/main/kotlin/build/buf/intellij/module/cache/ModuleCacheV3.kt
On MacOS there are multiple tickets regarding plugins and tooling not being able to access the full shell environment:
* https://youtrack.jetbrains.com/issue/IDEA-347154/The-installed-plugin-doesnt-have-access-to-environment-variables
* https://youtrack.jetbrains.com/issue/IJPL-11674/On-Mac-OS-X-IDE-doesnt-pick-up-shell-environment-when-started-from-Dock-Spotlight
The lack of environment variables causes this plugin to fail to resolve modules when the buf cache is in a non-standard location.
One of the workarounds is to modify the `environment.plist` (see [stackoverflow example](https://stackoverflow.com/questions/25385934/setting-environment-variables-via-launchd-conf-no-longer-works-in-os-x-yosemite/26586170#26586170)) which is tedious for end users.
Using `EnvironmentUtil` resolves …
> Use EnvironmentUtil helpers for module cache

- build.gradle.kts
- gradle/libs.versions.toml
Update the IntelliJ platform plugin to the latest 2.9.0. Add a new set of IDE ranges to test with plugin verification (existing `recommended()` is no longer working with the latest version). This will ensure we test with the full version range we support.
> Update IntelliJ platform plugin to latest
